### ISSUE TITLE
Set Initial state

### ISSUE THREAD

**Issue by fxv** [meteor-templ/tree#1]
After trying to accomplish something similar, I'm glad to discover this great package. I can't tell from the documentation how to set the initial state of the tree using the default States. I'd like to start with all the parents closed and toggle when needed. Any suggestions on how to accomplish this? Thank you.

**Comment by ivansglazunov** [comment]
Thank you for Issue!
Added optional argument `closed` to `Template[Tree.State]` and `insertState` method in version 0.0.3.

``` html
{{> Tree.State document=this States=States closed=true}}
```

**Comment by ivansglazunov** [comment]
Or you can create custom States collection with custom SimpleSchema.

``` js
collection.attachTemplTreeStatesGraph({
    schema: false
});
collection.attachSchema(new SimpleSchema({
    _source: { type: Shuttler.Ref.Schema, optional: true },
    _target: { type: Shuttler.Ref.Schema },
    closed: { type: Boolean, optional: true, defaultValue: true /*by default in this package: false*/ }
}));
```

**Comment by fxv** [comment]
Works great thank you. I'm planning to use the custom states in another prototype. Thank you again.

**Comment by ivansglazunov** [comment]
I will be glad to add links to other packages or prototypes in the `readme.md`.
